import {Analytics} from '@vercel/analytics/react';
import "@/styles/globals.scss";
import "@/styles/markdown.scss";
import "@/styles/highlight.scss";
import React from "react";


export const metadata = {
    title: 'Mojo AI',
    description: 'Generated by neochau@gmail.com',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {


    return (
        <html lang="en">
        <body>
        {children}
        <Analytics/>
        </body>
        </html>
    )
}
